import React from 'react';

export const metadata = {
    title: "About | My Next App",
    description: "Generated by create next app",
  };

const AboutPage = () => {
    return (
        <div>
            this is about page
        </div>
    );
};

export default AboutPage;