import React from 'react';
export const metadata = {
    title: "Add-Product | My Next App",
    description: "Generated by create next app",
  };

const AddProductPage = () => {
    return (
        <div>
            <h1>this is add product page</h1>
        </div>
    );
};

export default AddProductPage;