import React from 'react';
export const metadata = {
    title: "Manage-Product | My Next App",
    description: "Generated by create next app",
  };

const ManageProductPage = () => {
    return (
        <div>
            <h1>this is manage product page</h1>
        </div>
    );
};

export default ManageProductPage;