import React from 'react';
export const metadata = {
    title: "Profile | My Next App",
    description: "Generated by create next app",
  };
const ProfilePage = () => {
    return (
        <div>
            <h1>this is profile page</h1>
        </div>
    );
};

export default ProfilePage;