import React from 'react';
export const metadata = {
    title: "Dashboard | My Next App",
    description: "Generated by create next app",
  };

const DashboardPage = () => {
    return (
        <div>
            <h1>this is Dashboardpage</h1>
        </div>
    );
};

export default DashboardPage;